### ISSUE TITLE
Not compatible with latest release of Scriptable Object Collection

### ISSUE THREAD

**Issue by sezdev** [brunomikoski/UIManager#3]
In InitialSetupEditorWindow.cs:
`CollectionsRegistry.Instance.TryGetCollectionFromType` should be renamed to `CollectionsRegistry.Instance.TryGetCollectionOfType`

`ScriptableObjectCollectionSettings.Instance.SetGenerateCustomStaticFile` cannot be found since you refactored the settings on SOC and I don't know how to fix it myself, because I cannot find out what you did with it.

**Comment by brunomikoski** [comment]
Hey! I'm still working on this UIManager, it should have a new version quite soon, but for now I would suggest that you would not use the updated version of the SCO

**Comment by brunomikoski** [comment]
Fixed on #4
